module QBXML
  module ModelMaps
    Vendor = {
      :list_id => 'ListID',
      :time_created => 'TimeCreated',
      :time_modified => 'TimeModified',
      :edit_sequence => 'EditSequence',
      :name => 'Name',
      :is_active => 'IsActive',
      :is_tax_agency => 'IsTaxAgency',
      :company_name => 'CompanyName',
      :salutation => 'Salutation',
      :first_name => 'FirstName',
      :middle_name => 'MiddleName',
      :last_name => 'LastName',
      :suffix => 'Suffix',
      :vendor_address_addr1 => 'VendorAddress/Addr1',
      :vendor_address_addr2 => 'VendorAddress/Addr2',
      :vendor_address_addr3 => 'VendorAddress/Addr3',
      :vendor_address_addr4 => 'VendorAddress/Addr4',
      :vendor_address_addr5 => 'VendorAddress/Addr5',
      :vendor_address_city => 'VendorAddress/City',
      :vendor_address_state => 'VendorAddress/State',
      :vendor_address_postal_code => 'VendorAddress/PostalCode',
      :vendor_address_country => 'VendorAddress/Country',
      :vendor_address_note => 'VendorAddress/Note',
      :vendor_address_block_addr1 => 'VendorAddressBlock/Addr1',
      :vendor_address_block_addr2 => 'VendorAddressBlock/Addr2',
      :vendor_address_block_addr3 => 'VendorAddressBlock/Addr3',
      :vendor_address_block_addr4 => 'VendorAddressBlock/Addr4',
      :vendor_address_block_addr5 => 'VendorAddressBlock/Addr5',
      :phone => 'Phone',
      :mobile => 'Mobile',
      :pager => 'Pager',
      :alt_phone => 'AltPhone',
      :fax => 'Fax',
      :email => 'Email',
      :contact => 'Contact',
      :alt_contact => 'AltContact',
      :name_on_check => 'NameOnCheck',
      :account_number => 'AccountNumber',
      :notes => 'Notes',
      :vendor_type_ref_list_id => 'VendorTypeRef/ListID',
      :vendor_type_ref_full_name => 'VendorTypeRef/FullName',
      :terms_ref_list_id => 'TermsRef/ListID',
      :terms_ref_full_name => 'TermsRef/FullName',
      :credit_limit => 'CreditLimit',
      :vendor_tax_ident => 'VendorTaxIdent',
      :is_vendor_eligible_for1099 => 'IsVendorEligibleFor1099',
      :balance => 'Balance',
      :billing_rate_ref_list_id => 'BillingRateRef/ListID',
      :billing_rate_ref_full_name => 'BillingRateRef/FullName'
    }
  end
end
